"""Application ports; domain services do not depend on SQLite or HTTP."""

from contextlib import AbstractContextManager
from typing import Protocol


class Repository(Protocol):
    def atomic(self) -> AbstractContextManager: ...
    def get(self, kind: str, identifier: str) -> dict: ...
    def list(self, kind: str, project_id: str | None = None) -> list[dict]: ...
    def save(self, kind: str, record: dict) -> None: ...
    def audit(self, event: dict) -> None: ...
